#ifndef BASELINE_CONTROL_MESSAGE_H
#define BASELINE_CONTROL_MESSAGE_H

#include "ns3/tag.h"
#include "ns3/packet.h"

namespace ns3 {

/**
 * \brief Tag to mark a data packet with ECN congestion indication.
 *
 * Applied by BaselineCongestionDetector at the switch when queue
 * occupancy exceeds the congestion threshold. The receiver inspects
 * this tag and, if present and marked, generates a CNP back to the sender.
 */
class EcnTag : public Tag {
public:
  static TypeId GetTypeId (void);
  virtual TypeId GetInstanceTypeId (void) const;
  virtual uint32_t GetSerializedSize (void) const;
  virtual void Serialize (TagBuffer i) const;
  virtual void Deserialize (TagBuffer i);
  virtual void Print (std::ostream &os) const;

  EcnTag ();
  EcnTag (bool congestionExperienced);

  void SetCongestionExperienced (bool ce);
  bool GetCongestionExperienced (void) const;

private:
  bool m_congestionExperienced;
};

/**
 * \brief Header for Congestion Notification Packet (CNP).
 *
 * Generated by the receiver when it detects an ECN-marked data packet.
 * Contains the flowId of the congested flow so the sender can identify
 * which flow to throttle.
 */
class CnpHeader : public Header {
public:
  static TypeId GetTypeId (void);
  virtual TypeId GetInstanceTypeId (void) const;
  virtual uint32_t GetSerializedSize (void) const;
  virtual void Serialize (Buffer::Iterator start) const;
  virtual uint32_t Deserialize (Buffer::Iterator start);
  virtual void Print (std::ostream &os) const;

  CnpHeader ();
  CnpHeader (uint32_t flowId);

  void SetFlowId (uint32_t flowId);
  uint32_t GetFlowId (void) const;

private:
  uint32_t m_flowId;
};

} // namespace ns3

#endif /* BASELINE_CONTROL_MESSAGE_H */
