#ifndef FLOWSTAR_CONTROL_MESSAGE_H
#define FLOWSTAR_CONTROL_MESSAGE_H

#include "ns3/header.h"
#include "flowstar-mid.h"

namespace ns3 {

/**
 * \brief CNP (Congestion Notification Packet) for FlowStar.
 *
 * Generated by the receiver and sent to the sender when endpoint
 * congestion is detected. It explicitly carries the measured
 * receiving rate.
 */
class FlowStarCnpHeader : public Header
{
public:
  static TypeId GetTypeId (void);
  virtual TypeId GetInstanceTypeId (void) const;

  FlowStarCnpHeader ();
  FlowStarCnpHeader (FlowStarMid mid, uint64_t rateBps, uint64_t timestamp);
  virtual ~FlowStarCnpHeader ();

  virtual void Print (std::ostream &os) const;
  virtual uint32_t GetSerializedSize (void) const;
  virtual void Serialize (Buffer::Iterator start) const;
  virtual uint32_t Deserialize (Buffer::Iterator start);

  FlowStarMid GetMid (void) const { return m_mid; }
  uint64_t    GetReceivingRateBps (void) const { return m_receivingRateBps; }
  uint64_t    GetTimestamp (void) const { return m_timestamp; }

private:
  FlowStarMid m_mid;
  uint64_t    m_receivingRateBps;
  uint64_t    m_timestamp;
};

/**
 * \brief BECN (Backward Explicit Congestion Notification) for FlowStar.
 *
 * Generated by the switch and sent directly to the sender when
 * fabric congestion is detected (queue occupancy > threshold).
 * Carries the queue occupancy and the identity of the congested switch.
 */
class FlowStarBecnHeader : public Header
{
public:
  static TypeId GetTypeId (void);
  virtual TypeId GetInstanceTypeId (void) const;

  FlowStarBecnHeader ();
  FlowStarBecnHeader (FlowStarMid mid, uint32_t queueOccupancy, uint32_t switchId);
  virtual ~FlowStarBecnHeader ();

  virtual void Print (std::ostream &os) const;
  virtual uint32_t GetSerializedSize (void) const;
  virtual void Serialize (Buffer::Iterator start) const;
  virtual uint32_t Deserialize (Buffer::Iterator start);

  FlowStarMid GetMid (void) const { return m_mid; }
  uint32_t    GetQueueOccupancy (void) const { return m_queueOccupancy; }
  uint32_t    GetSwitchId (void) const { return m_switchId; }

private:
  FlowStarMid m_mid;
  uint32_t    m_queueOccupancy;
  uint32_t    m_switchId;
};

} // namespace ns3

#endif /* FLOWSTAR_CONTROL_MESSAGE_H */
